export const EMPTY_PUSH_PENALTY = 70
export const WRONG_BRANCH_PUSH_PENALTY = 60
export const INCOMPLETE_WORKFLOW_PENALTY = 50
export const MISSING_TOPPING_PENALTY = 30
export const SUCCESS_DELIVERY_POINT = 100
