services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: gitramen_backend
    volumes:
      - sqlite_data:/app/db
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: gitramen_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always

volumes:
  sqlite_data: