services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: gitramen_backend
    volumes:
      - sqlite_data:/app/db
    restart: always
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: gitramen_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always

  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    depends_on:
      - nginx
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
  
  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend



volumes:
  sqlite_data: